Equipement/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.accueil),
    path('map/',views.map,name='map'),
    path('ajouter/', views.ajouter_equipement, name='ajouter_equipement'),
    path('import-csv/', views.import_csv, name='import_csv'),
    path('showEquipement/', views.showEquipement, name='showEquipement'),
    path('supprimer_equipement/<str:pk>', views.supprimer_equipement, name='supprimer_equipement'),
    path('search/', views.search_equipments, name='search_equipments'),
    path('equipements/<int:equipement_id>/modifier/', views.modifier_etat, name='modifier_etat'),
]

Projet_GQ/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Equipement.urls')),
    path('Laboratoire/',include('Laboratoire.urls')),
    path('Etablissement/',include('Etablissement.urls')),
    path('Visiteur/',include('Visiteur.urls')),
    path('compte/',include('compte.urls')),
]

compte/urls.py
from django.urls import path
from .views import activate  
from . import views

urlpatterns = [
    path('inscription',views.signup , name= 'inscription'),
    path('connexion',views.accesPage , name= 'connexion'),
    path('quitter',views.logoutUser, name='quitter'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',  
        activate, name='activate'),  
]

Equipement/models.py
from django.db import models
from Laboratoire.models import Laboratoire
from auditlog.models import AuditlogHistoryField

class Equipement(models.Model):
    ETAT_CHOICES = (
        ('Installé', 'Installé'),
        ('en panne', 'En panne'),
        ('Fonctionnel', 'Fonctionnel')
    )
    CATEGORIE_CHOICES = (
    ('Chimie', 'Chimie'),
    ('Biologie', 'Biologie'),
    ('Microbiologie', 'Microbiologie'),
    ('Biotechnologie', 'Biotechnologie'),
    ('Autre', 'Autre')
)
    Reference = models.CharField(max_length=200, unique=True, null=True)
    Etat = models.CharField(max_length=200, null=True, choices=ETAT_CHOICES)
    Date_Acquisition = models.DateField(auto_now_add=True)
    Marque = models.CharField(max_length=200, null=True)
    Laboratoire = models.ForeignKey(Laboratoire, on_delete=models.CASCADE)
    Categorie = models.CharField(max_length=200, choices=CATEGORIE_CHOICES)  # Ajoutez ce champ
    history = AuditlogHistoryField()  
  
    def __str__(self):
        return self.Reference

Equipement/forms.py
from django.forms import ModelForm
from .models import Equipement

class EquipementForm(ModelForm):
    class Meta:
        model=Equipement
        fields='__all__'

Equipement/views.py
from django.http import HttpResponse
import csv
import os
from Equipement.filters import EquipementFiltre
from django.contrib import messages
from django.shortcuts import render, redirect
from .models import Equipement
from Laboratoire.models import Laboratoire
from Visiteur.models import Visiteur
from .forms import EquipementForm
from Etablissement.models import Etablissement
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required(login_url='connexion')
def accueil(request):
    equipements = Equipement.objects.all()
    laboratoires= Laboratoire.objects.all()
    visiteurs = Visiteur.objects.all()
    total_equipements = equipements.count()
    total_laboratoires= laboratoires.count()
    total_visiteurs = visiteurs.count() 
    derniers_equipements = equipements.order_by('-Date_Acquisition')[:3]
 

    context = {
        'total_equipements': total_equipements,
        'total_laboratoires': total_laboratoires,
        'equipements': equipements,
        'derniers_equipements': derniers_equipements,
        'visiteurs':visiteurs,
        'total_visiteurs': total_visiteurs,
    }
    return render(request, 'Equipement/dashboard.html', context)




@login_required(login_url='connexion')

def showEquipement(request):
    equipements = Equipement.objects.all()

    # Récupérer toutes les marques distinctes existantes
    marques_distinctes = Equipement.objects.values_list('Marque', flat=True).distinct()

    context = {
        'equipements': equipements,
        'marques_distinctes': marques_distinctes,
    }

    return render(request, 'Equipement/xmateriel.html', context)


@login_required(login_url='connexion')
def map(request):
    return render(request,'Equipement/map.html')

@login_required(login_url='connexion')   
def import_csv(request):
    if request.method == 'POST' and request.FILES.get('csv_file'):
        csv_file = request.FILES['csv_file']
        file_extension = csv_file.name.split('.')[-1]
        if file_extension.lower() != 'csv':
            # Ajoutez un message d'erreur si l'extension n'est pas valide
            messages.error(request, "L'extension du fichier n'est pas valide. Veuillez sélectionner un fichier CSV.")
            return render(request, 'Equipement/import_csv.html')

        try:
            decoded_file = csv_file.read().decode('iso-8859-1')  # Utilisez l'encodage ISO-8859-1 (latin-1) pour lire le fichier CSV
            csv_data = csv.reader(decoded_file.splitlines(), delimiter=',')

            for row in csv_data:
                # Vérifiez que toutes les données nécessaires sont présentes dans la ligne du CSV
                if len(row) >= 13:
                    # Récupérez les données de chaque colonne
                    reference = row[0]
                    etat = row[1]
                    marque = row[2]
                    date_acquisition = row[3]
                    laboratoire_name = row[4]
                    localisation = row[5]
                    telephone = row[6]
                    email = row[7]
                    abrv = row[8]
                    etablissement_name = row[9]
                    adresse = row[10]
                    etablissement_telephone = row[11]
                    etablissement_email = row[12]

                    # Recherchez l'établissement correspondant dans la base de données en utilisant le nom de l'établissement
                    try:
                        etablissement = Etablissement.objects.get(Nom_Etab=etablissement_name)
                    except Etablissement.DoesNotExist:
                        # Si l'établissement n'existe pas, créez-le et enregistrez-le dans la base de données
                        etablissement = Etablissement.objects.create(
                            Nom_Etab=etablissement_name,
                            Adresse=adresse,
                            telephone=etablissement_telephone,
                            email=etablissement_email
                        )
                    
                    # Vérifiez si le laboratoire existe déjà dans la base de données
                    laboratoire_exists = Laboratoire.objects.filter(Nom_Lab=laboratoire_name).exists()
                    if laboratoire_exists:
                        messages.warning(request, f"Le laboratoire '{laboratoire_name}' existe déjà dans la base de données. Le laboratoire et l'équipement ne seront pas importés.")
                        continue

                    # Créez une instance de Laboratoire et enregistrez-la dans la base de données
                    laboratoire = Laboratoire.objects.create(
                        Nom_Lab=laboratoire_name,
                        Localisation=localisation,
                        Telephone=telephone,
                        Email=email,
                        Abrv=abrv,
                        Etablissement=etablissement
                    )

                    # Créez une instance d'Equipement et enregistrez-la dans la base de données
                    Equipement.objects.create(
                        Reference=reference,
                        Etat=etat,
                        Date_Acquisition=date_acquisition,
                        Marque=marque,
                        Laboratoire=laboratoire
                    )
        
            # Redirigez ou renvoyez une réponse appropriée en fonction de votre besoin
            messages.success(request, 'Importation CSV réussie.')
            return redirect('showEquipement')  # Remplacez 'showEquipement' par le nom de la vue que vous souhaitez afficher après l'importation réussie.

        except Exception as e:
            messages.error(request, 'Une erreur s\'est produite lors de l\'importation du fichier CSV. Veuillez vérifier le format et l\'encodage du fichier.')
            return render(request, 'Equipement/import_csv.html')

    return render(request, 'Equipement/import_csv.html')

@login_required(login_url='connexion')
def ajouter_equipement(request):
    form = EquipementForm()
    if request.method == 'POST': 
        form=EquipementForm(request.POST)
        if form.is_valid():
           form.save()
           return redirect('showEquipement')
    context={'form':form}
    return render(request, 'Equipement/ajouter_equipement.html',context)

@login_required(login_url='connexion')
def supprimer_equipement(request,pk):
    equipement=Equipement.objects.get(Reference=pk)
    if request.method == 'POST':
        equipement.delete()
        return redirect('showEquipement')
    context ={'item':equipement}
    return render(request,'Equipement/supprimer_equipement.html',context)

@login_required(login_url='connexion')
def search_equipments(request):
    search_query = request.GET.get('Marque')  
    equipements = Equipement.objects.all()

    if search_query:
        equipement_filter = EquipementFiltre(request.GET, queryset=equipements)
        equipements = equipement_filter.qs
    return render(request, 'Equipement/rechercher.html', {'equipements': equipements})

def modifier_etat(request, equipement_id):
    equipement = Equipement.objects.get(id=equipement_id)

    if request.method == 'POST':
        nouvel_etat = request.POST['nouvel_etat']
        equipement.Etat = nouvel_etat
        equipement.save()
        return redirect('showEquipement')
    
    return render(request, 'Equipement/modifier_etat.html', {'equipement': equipement})

templates/Equipement/accueil.html
{% extends 'main.html' %}
{% block content %}

<br>



{% endblock content%}

templates/Equipement/ajouter_equipement.html
{% extends 'main.html' %}
{% block content %}
<!-- Inclure les liens vers les fichiers CSS de Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

<!-- Votre code HTML pour le formulaire d'ajout d'équipement -->
<form method="POST" action="">
    {% csrf_token %}
    <div class="form-group">
    {{form}}</div>
    <button type="submit" class="btn btn-primary"><i class="fas fa-plus"></i> Ajouter</button>
    <a href="{% url 'import_csv' %}" class="btn btn-secondary"><i class="fas fa-file-csv"></i> Importer un fichier CSV</a>
</form>

<!-- Inclure les liens vers les fichiers JavaScript de Font Awesome -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js"></script>

<style>
    /* Ajoutez du style personnalisé ici */
    body {
        background-color: #f5f5f5;
        font-family: Arial, sans-serif;
    }
    
    form {
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        margin-top: 100px;
    }
    
    .form-group {
        margin-bottom: 20px;
 
    }
    
    label {
        font-weight: bold;
    }
    
    input[type="text"],
    select {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        font-size: 16px;
    }
    
    button {
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        font-size: 16px;
        color: #fff;
        background-color: #007bff;
        cursor: pointer;
    }
    

</style>
{% endblock content%}

templates/Equipement/dashboard.html
{% extends 'main.html' %}
{% block content %}
<style>
/* Main styles for the dashboard */
.dashboard {
  padding: 20px;
}

.top {
  display: flex;
  justify-content: flex-end;
  margin-bottom: 20px;
}

.dash-content {
  border-radius: 8px;
  padding: 20px;
  margin-left: 250px;
  margin-right: 90px;
}

.title {
  display: flex;
  align-items: center;
  font-size: 24px;
  font-weight: bold;
  margin-bottom: 20px;
}

.boxes {
  display: flex;
  justify-content: space-between;
  flex-wrap: wrap;
}

.box {
  background-color: #f0f0f0;
  border-radius: 8px;
  padding: 20px; /* Reduced padding */
  margin-bottom: 20px;
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
  flex-basis: calc(33.33% - 20px); /* Set to 33.33% to fit three boxes in a row */
  transition: transform 0.2s;
  cursor: pointer; /* Added cursor pointer on hover */
}

.box:hover {
  transform: scale(1.1); /* Increased the scale on hover */
}

.box span {
  display: block;
  margin-top: 10px;
}

.activity {
  margin-top: 40px;
}

.activity-data {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 10px;
}

.data {
  background-color: #ffffff;
  border-radius: 8px;
  padding: 20px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.data-title {
  font-weight: bold;
  margin-bottom: 10px;
}

/* Custom styles for icons */
.bxs-eyedropper {
  font-size: 32px;
  margin-right: 10px;
  color: #06aaf5;
}

.icon-lab {
  font-size: 32px;
  margin-right: 10px;
  color: #06aaf5;
}

.fa-clock-rotate-left {
  font-size: 27px;
  margin-right: 10px;
  color: #0e0f0f;
}

/* Table styles */
.table {
  width: 100%;
  border-collapse: collapse;
  background-color: #ffffff;
}
.fa-users{
  font-size: 32px;
  margin-right: 10px;
  color: #06aaf5;
}

.bxs-eyedropper {
  font-size: 32px;
  margin-right: 10px;
  color: #06aaf5;
}
.bxs-dashboard {
  font-size: 32px;
  margin-right: 10px;
  color: #0e0f0f;
}

.table th,
.table td {
  padding: 12px;
  text-align: left;
  border-bottom: 1px solid #ddd;
}

.table th {
  background-color: #f0f0f0;
}

</style>

<div class="top">
  <i class="bx bx-menu sidebar-toggle"></i>
</div>
<div class="dash-content">
  <div class="overview">
    <div class="title">
      <i class="bx bxs-dashboard"></i>
      <span class="text">Tableau de bord</span>
    </div>
    <div class="boxes">
      <div class="box box1">
        <i class='bx bxs-eyedropper'></i>
        <span class="text">Équipements</span>
        <span class="number">{{ total_equipements }}</span>
      </div>
      <div class="box box2">
        <i class="fas fa-flask icon-lab"></i> 
        <span class="text">Total des laboratoires scientifiques</span>
        <span class="number">{{ total_laboratoires }}</span>
      </div>
      <div class="box box2">
        <i class="fa-solid fa-users"></i>
        <span class="text">Total des visiteurs</span>
        <span class="number">{{total_visiteurs}}</span>
      </div>
    </div>
  </div>
  <div class="activity">
    <div class="title">
      <i class="fa-solid fa-clock-rotate-left"></i>
      <span class="text">Les trois derniers équipements ajoutés</span>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th>Identifiant</th>
          <th>Nom d'équipement</th>
          <th>Date d'acquisition</th>
        </tr>
      </thead>
      <tbody>
        {% for equipement in derniers_equipements %}
        <tr>
          <td>{{ equipement.Reference }}</td>
          <td>{{ equipement.Marque }}</td>
          <td>{{ equipement.Date_Acquisition }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>


{% endblock content%}

templates/Equipement/import_csv.html
{% extends 'main.html' %}
{% block content %}
<!-- Inclure les liens vers les fichiers CSS de Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

<!-- Votre code HTML pour le formulaire d'importation de fichier CSV -->
<form method="post" action="{% url 'import_csv' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        <label for="csv_file">Choisir un fichier CSV à importer :</label>
        <input type="file" id="csv_file" name="csv_file" style="display: none;">
        <label for="csv_file" class="btn btn-secondary"><i class="fas fa-file-upload"></i> Choisir un fichier</label>
       <button type="submit" class="btn btn-primary"><i class="fas fa-upload"></i> Importer</button>
 </div>
</form>
{% if messages %}
    <div class="messages-container">
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
{% endif %}
<!-- Inclure les liens vers les fichiers JavaScript de Font Awesome -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js"></script>

<style>
    /* Ajoutez du style personnalisé ici */
    body {
        background-color: #f5f5f5;
        font-family: Arial, sans-serif;
    }
    
    form {
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        margin-top: 100px;
    }
    
    label {
        font-weight: bold;
    }
    
    input[type="file"] {
        display: none;
    }
    
    button {
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        font-size: 16px;
        color: #fff;
        background-color: #007bff;
        cursor: pointer;
    }
        /* Custom style for error messages */
        .messages-container {
        max-width: 400px;
        margin: 10px auto;
        padding: 10px;
        background-color: #f8d7da; /* Light red background color for error messages */
        border-color: #f5c6cb; /* Border color for error messages */
        color: #721c24; /* Text color for error messages */
        border-radius: 5px;
        box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
    }
    
    .messages {
        list-style: none;
        padding: 0;
        margin: 0;
    }
    
    .messages li {
        padding: 5px;
        margin-bottom: 5px;
    }
    
    .error {
        color: #721c24; /* Text color for error messages */
    }
    
    .info {
        color: #0056b3; /* Text color for info messages */
    }
    
    .success {
        color: #155724; /* Text color for success messages */
    }
    
    .warning {
        color: #856404; /* Text color for warning messages */
    }
 
</style>
{% endblock content%}

templates/Equipement/modifier_etat.html
{% extends 'main.html' %}
{% load static %}

{% block content %}
  <body>
    <div class="container" style="margin-left: 500px; margin-top: 200px; max-width: 600px; padding: 20px; border-radius: 8px; background-color: #fff; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); animation: slide-in 0.5s ease;">
      <h2 style="font-size: 18px;"><i class="fas fa-cogs" style="margin-right: 10px;"></i> Modifier l'état de l'équipement {{ equipement.Reference }}</h2>
      <form method="post">
        {% csrf_token %}
        <label for="nouvel_etat"><i class="fas fa-exclamation-circle" style="margin-right: 10px;"></i> Nouvel état :</label>
        <select name="nouvel_etat">
          <option value="Installé"><i class="fas fa-check" style="margin-right: 5px;"></i> Installé</option>
          <option value="en panne"><i class="fas fa-exclamation-triangle" style="margin-right: 5px;"></i> En panne</option>
          <option value="Fonctionnel"><i class="fas fa-check-circle" style="margin-right: 5px;"></i> Fonctionnel</option>
        </select>
        <button type="submit" class="btn-save"><i class="fas fa-save" style="margin-right: 5px;"></i> Modifier</button>
      </form>
    </div>

    <style>
      @keyframes slide-in {
        from {
          opacity: 0;
          transform: translateY(-20px);
        }
        to {
          opacity: 1;
          transform: translateY(0);
        }
      }

      label {
        display: flex;
        align-items: center;
        margin-bottom: 10px;
      }

      select,
      button {
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
        background-color: #fff;
        font-size: 16px;
        transition: box-shadow 0.3s ease;
      }

      select:focus,
      button:focus {
        outline: none;
        box-shadow: 0 0 5px #007BFF;
      }

      .btn-save {
        background-color: #007BFF;
        color: #fff;
        font-weight: bold;
        cursor: pointer;
      }

      .btn-save:hover {
        background-color: #0056b3;
      }
    </style>
  </body>
{% endblock content %}

templates/Equipement/rechercher.html
{% extends 'main.html' %}
{% block content %}
<body>
{% if equipements %}
<ul>
    {% for equipement in equipements %}
     
            <strong>Reference:</strong> {{ equipement.Reference }}<br>
            <strong>Etat:</strong> {{ equipement.get_Etat_display }}<br>
            <strong>Date d'Acquisition:</strong> {{ equipement.Date_Acquisition }}<br>
            <strong>Marque:</strong> {{ equipement.Marque }}<br>
            <strong>Laboratoire:</strong> {{ equipement.Laboratoire }}<br>
            <strong> Ville de Laboratoire: </strong> {{ equipement.Laboratoire.Localisation}}
         
      
    {% endfor %}
</ul>
{% else %}
<p>Aucun résultat trouvé pour la recherche.</p>
{% endif %}</body>
<style>

    body{
    margin-left: 300px; 
    margin-top: 20px;}
       </style>
{% endblock content %}

templates/Equipement/supprimer_equipement.html
{% extends 'main.html' %}

{% block content %}
    <div class="container" style="margin-left: 300px;">
       
        <p class="lead">Êtes-vous sûr de vouloir supprimer l'équipement {{ item.Reference }} ?</p>
        <form action="{% url 'supprimer_equipement' item.Reference %}" method="POST">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="Confirmer">
            <a href="{% url 'showEquipement' %}" class="btn btn-warning"><i class="fas fa-times"></i> Annuler</a>
        </form>
    </div>
    <style>
        body {
            background-color: #f5f5f5;
            font-family: Arial, sans-serif;
            font-weight: bold;
        }
    
        .container {
            margin-top: 50px;
            padding: 20px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
    
     
    
        p {
            color: #333;
        }
    
        form {
            margin-top: 20px;
        }
    
        .btn {
            margin-right: 10px;
        }
    </style>
    
{% endblock content %}

templates/Equipement/xmateriel.html
{% extends 'main.html' %}

{% block content %}
<!-- Inclure les liens vers les fichiers CSS de Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

<!-- Filtre par catégorie -->
<div class="container">
    <label for="categorie">Filtrer par catégorie :</label>
    <select id="categorie">
        <option value="">Toutes</option>
        <option value="Chimie">Chimie</option>
        <option value="Biologie">Biologie</option>
        <option value="Microbiologie">Microbiologie</option>
        <option value="Biotechnologie">Biotechnologie</option>
        <option value="Autre">Autre</option>
    </select>
</div>
<div class="container">
    <label for="marque">Filtrer par marque :</label>
    <select id="marque">
        <option value="">Toutes</option>
        {% for marque in marques_distinctes %}
            <option value="{{ marque }}">{{ marque }}</option>
        {% endfor %}
    </select>
</div>


<!-- Tableau des équipements -->
<div class="container">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Référence</th>
                <th>État</th>
                <th>Date d'acquisition</th>
                <th>Marque</th>
                <th>Catégorie</th> <!-- Modifier le titre de la colonne -->
                <th>Laboratoire</th>
                <th>Supprimer</th>
                <th>Modifier</th>
            </tr>
        </thead>
        <tbody>
            {% for equipement in equipements %}
            <tr data-categorie="{{ equipement.Categorie }}" data-marque="{{ equipement.Marque }}">
                <td>{{ equipement.Reference }}</td>
                <td>
                    {% if equipement.Etat == 'en panne' %}
                        <span style="color: red;"><i class="fas fa-exclamation-circle"></i> En panne</span>
                    {% elif equipement.Etat == 'Fonctionnel' %}
                        <span style="color: green;"><i class="fas fa-check-circle"></i> Fonctionnel</span>
                    {% elif equipement.Etat == 'Installé' %}
                        <span style="color: blue;"><i class="fas fa-cogs"></i> Installé</span>
                    {% endif %}
                </td>
                <td>{{ equipement.Date_Acquisition }}</td>
                <td>{{ equipement.Marque }}</td>
                <td>{{ equipement.Categorie }}</td>
                {% for categorie in categories %}
                <button class="filter-btn {% if selected_category == categorie %}active-filter{% endif %}">{{ categorie }}</button>
                {% endfor %}
                <td>{{ equipement.Laboratoire }}</td>
                <td>
                    <a href="{% url 'supprimer_equipement' equipement.Reference %}" class="btn btn-danger"><i class="fas fa-trash"></i></a>
                </td>
                <td>
                    <a href="{% url 'modifier_etat' equipement.id %}" class="btn btn-primary"><i class="fas fa-pencil-alt"></i></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- Bouton pour ajouter un nouvel équipement -->
    <a href="{% url 'ajouter_equipement' %}" class="btn btn-primary"><i class="fas fa-plus"></i> Ajouter un nouvel équipement</a>
</div>

<!-- Inclure les liens vers les fichiers JavaScript de Font Awesome -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js"></script>

<script>
    // Fonction pour filtrer les équipements en fonction de la catégorie et de la marque sélectionnées
    function filtrerEquipements() {
        const selectCategorie = document.getElementById('categorie');
        const selectedCategorie = selectCategorie.value;

        const selectMarque = document.getElementById('marque');
        const selectedMarque = selectMarque.value;

        const equipements = document.querySelectorAll('tr[data-categorie][data-marque]');

        equipements.forEach((equipement) => {
            const categorie = equipement.getAttribute('data-categorie');
            const marque = equipement.getAttribute('data-marque');

            const categorieMatch = selectedCategorie === '' || categorie === selectedCategorie;
            const marqueMatch = selectedMarque === '' || marque === selectedMarque;

            if (categorieMatch && marqueMatch) {
                equipement.style.display = 'table-row';
            } else {
                equipement.style.display = 'none';
            }
        });
    }

    const selectCategorie = document.getElementById('categorie');
    selectCategorie.addEventListener('change', filtrerEquipements);

    const selectMarque = document.getElementById('marque');
    selectMarque.addEventListener('change', filtrerEquipements);
</script>

<style>
    body {
        background-color: #E4E9F7; 
        font-family: Arial, sans-serif;
    }

    table {
        margin: 20px auto;
        border-collapse: collapse;
        width: 100%;
    }
    
    .container {
        margin: 20px 300px; 
    }

    th,
    td {
        border: 10px solid #000000; 
        padding: 10px;
        text-align: center;
        background-color: #fff; 
    }

    th {
        background-color: #f2f2f2;
    }

    tr:nth-child(even) td {
        background-color: #f9f9f9;
    }

    td span {
        padding: 4px 8px;
        border-radius: 4px;
        font-weight: bold;
    }

    td span.en-panne {
        color: red;
        background-color: #fde6e6;
    }

    td span.fonctionnel {
        color: green;
        background-color: #e3fcec;
    }

    td span.installe {
        color: blue;
        background-color: #e4f4fd;
    }

    .btn {
        margin-top: 20px;
    }
.filter-btn {
  padding: 8px 16px;
  border: 1px solid #ccc;
  border-radius: 4px;
  background-color: #fff;
  color: #333;
  font-size: 14px;
  cursor: pointer;
  transition: background-color 0.3s ease;
}

.filter-btn:hover {
  background-color: #007BFF;
  color: #fff;
}

.active-filter {
  background-color: #007BFF;
  color: #fff;
}

</style>

{% endblock content %}